name: create-new-release

on:
  push:
    branches: [ $default-branch ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install unzip
      - run: wget "https://web.archive.org/web/20181016150224/https://download.steinberg.net/sdk_downloads/vstsdk3610_11_06_2018_build_37.zip" -O ${{github.workspace}}/Libraries/vstsdk/vstsdk.zip
      - run: unzip ${{github.workspace}}/Libraries/vstsdk/vstsdk.zip -d ${{github.workspace}}/Libraries/vstsdk/
      - run: cp ${{github.workspace}}/Libraries/vstsdk/VST_SDK/VST2_SDK/public.sdk/source/vst2.x/* ${{github.workspace}}/Libraries/vstsdk/
      - run: cp -a ${{github.workspace}}/Libraries/vstsdk/VST_SDK/VST2_SDK/pluginterfaces ${{github.workspace}}/Libraries/vstsdk/
      - run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      - run: rm -rf ${{github.workspace}}/Libraries/vstsdk/
